language: python
services:
- docker
before_script:
- export VERSION=$(awk '{print $3}' lib/src/spark_validation/version.py | sed 's/"//g')
before_install:
- docker pull covertspartan/docker-airflow-spark
install:
- pip install -r requirements.txt
script:
- cd lib
- pip install -r requirements.txt --quiet
- export PYTHONPATH="$PWD/src:$PWD/test:$PYTHONPATH"
deploy:
  provider: pypi
  user: ronaldsmithangel
  password:
    secure: LZnBL8dhXzc+ygWpPHWDboPKWJ/jW58fg5N8US7np9tRhZ9YQzwFtDjaHetVxmIBCM+h57DmA5kJNBaIx7saNu48wARBxsZTP7T3pnM8L5uMpJhwaqIYQdIbnh00FbzyintuQJ7LqkSNFhUMkkoAoW+1NXAr9lk0HdGbMeTxJmr9ZSh4131rQIfqury8pT8z27/kslSD61x3Gua+yqbhYns1ZwMwuR84t2uRC7ihScM2Bi/gmQusjTm5HXwChn1U+fh1GQPb63bREfPwfTlvAN5GYt8ZuV/A3lz4iTwm0eRMDpnE1cO4kJ92U0xxtjeixgE0Jz73KebAAYQp+4I1zv7ng3gPlyDSPRn98eLYy8e/zp1q15kO179dvb87l+7WzQ8gjfI1FXsNneAlv+Aza/EDOHmssrlFAhXQpG3rDLgIEBEQbAKQCYrFJt/1tQdFHGWtTl+pvW8l+nMca5pRttZsDkPHhfRft6H+P1YWcEL6ksngiFh979EjLnuVISZGjLJmAjF7M3pxDZT9qbBF8NHPxmMjUaKeyTg2kONyGLH2mtFOanRxdYJOurZeIOAZA1GPq8iqL0M/a1Eivr5MTLYHCU/WEvEBDOThVu88N/9Y24sTtnIdMckzBFSZ+SBqgmZOw1TlmY+MugrX0z009tW3zgEAsiNUR+eK5AfGrEc=
  on:
    branch: develop
