version: "3.7"
services:
    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - $PWD/logs:/logs/
